language: python

sudo: false

env:
  - TOX_ENV=flake8
  # Django 1.9
  - TOX_ENV=py34-dj19-cms32
  - TOX_ENV=py27-dj19-cms32
  # Django 1.8
  - TOX_ENV=py34-dj18-cms32
  - TOX_ENV=py34-dj18-cms31
  - TOX_ENV=py33-dj18-cms32
  - TOX_ENV=py33-dj18-cms31
  - TOX_ENV=py27-dj18-cms32
  - TOX_ENV=py27-dj18-cms31


install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
